/**
 * Example-theme Theme
 * Cloned from: https://example.com
 * Generated by: NestPress AI Theme Factory
 */

import React from 'react';
import { Post, Menu, Widget, HeaderSettings } from '../../types';

// Export Parts
export { Header } from './parts/Header';
export { Footer } from './parts/Footer';


// Export Types
export interface ThemeTemplateProps {
  data?: any;
  posts?: Post[];
  post?: Post;
  currentPage?: number;
  totalPages?: number;
  onPageChange?: (page: number) => void;
  menus?: Menu[];
  widgets?: Widget[];
  header?: HeaderSettings;
  primaryMenu?: Menu;
  footerMenu?: Menu;
  sidebarWidgets?: Widget[];
  footerWidgets?: Widget[];
  headerWidgets?: Widget[];
}

// Export Templates
export { default as IndexTemplate } from './templates/index';
export { default as SingleTemplate } from './templates/single';
export { default as PageTemplate } from './templates/page';
export { default as ArchiveTemplate } from './templates/archive';
export { default as CategoryTemplate } from './templates/category';
export { default as SearchTemplate } from './templates/search';
export { default as NotFoundTemplate } from './templates/404';

// Theme metadata
export const theme = {
  name: 'Example-theme',
  version: '1.0.0',
  author: 'AI Theme Factory',
  sourceUrl: 'https://example.com',
};
